#------------------------------------------------------------------------------
# GAP-Solver — An educational solver for the Generalized Assignment Problem
#              using MILP and heuristic methods.
#------------------------------------------------------------------------------
# Copyright (c) 2025 Josué Tambwe
#               Nantes Université, France
#------------------------------------------------------------------------------
# This software is released under the MIT License.
# See the LICENSE file for more details.
#------------------------------------------------------------------------------


# all source file of the gap subdirectory
gap_sources = files('GapInstance.cpp',
                    'GapSolver.cpp',
                    'Status.cpp',
                    'GapSolution.cpp')